;
; Resources
;
file_uploads = On
upload_max_filesize = 512M
post_max_size = 512M
max_execution_time = 300
memory_limit = 512M
max_input_vars = 3000

;
; Security
;
expose_php = Off
; allow_url_fopen = Off

;
; Error Logging (Routes to the shared logs/ folder on the host)
;
log_errors = On
error_log = /var/log/apache2/php_errors.log

;
; Display Errors (Uncomment 'On' and comment 'Off' for development)
;
display_errors = Off
; display_errors = On

;
; General settings
;
; Timezone list: https://gist.github.com/blacksmoke26/e61da22d9848a9580214
; date.timezone = "Asia/Bishkek"

; Execute the environment parser before any WordPress file loads
auto_prepend_file = /usr/local/etc/wp-env-parser.php
