ServerTokens Prod
ServerSignature Off

<VirtualHost *:80>
        ServerAdmin webmaster@localhost
        DocumentRoot /var/www/html

        # Essential for WordPress permalinks to function
        <Directory /var/www/html>
            Options FollowSymLinks
            AllowOverride All
            Require all granted
        </Directory>

        # Log real IP from Nginx proxy
        LogFormat "%{X-Forwarded-For}i %l %u %t \"%r\" %>s %b \"%{Referer}i\" \"%{User-Agent}i\"" proxy
        LogFormat "%h %l %u %t \"%r\" %>s %b \"%{Referer}i\" \"%{User-Agent}i\"" combined
        SetEnvIf X-Forwarded-For "^.*\..*\..*\..*" forwarded
        CustomLog "/var/log/apache2/access.log" combined env=!forwarded
        CustomLog "/var/log/apache2/access.log" proxy env=forwarded
        ErrorLog "/var/log/apache2/error.log"

        # Block access to xmlrpc.php (Apache 2.4 syntax)
        <Files xmlrpc.php>
            Require all denied
        </Files>

        # Block access to wp-config.php
        <Files wp-config.php>
            Require all denied
        </Files>
</VirtualHost>

<IfModule mod_ssl.c>
    <VirtualHost _default_:443>
        DocumentRoot /var/www/html

        <Directory /var/www/html>
            Options FollowSymLinks
            AllowOverride All
            Require all granted
        </Directory>

        LogFormat "%{X-Forwarded-For}i %l %u %t \"%r\" %>s %b \"%{Referer}i\" \"%{User-Agent}i\"" proxy
        LogFormat "%h %l %u %t \"%r\" %>s %b \"%{Referer}i\" \"%{User-Agent}i\"" combined
        SetEnvIf X-Forwarded-For "^.*\..*\..*\..*" forwarded
        CustomLog "/var/log/apache2/access.log" combined env=!forwarded
        CustomLog "/var/log/apache2/access.log" proxy env=forwarded
        ErrorLog "/var/log/apache2/error.log"

        SSLEngine on
        SSLCertificateFile      /etc/apache2/certs/ssl-cert.pem
        SSLCertificateKeyFile   /etc/apache2/certs/ssl-cert.key

        <Files xmlrpc.php>
            Require all denied
        </Files>

        <Files wp-config.php>
            Require all denied
        </Files>

        <FilesMatch "\.(cgi|shtml|phtml|php)$">
            SSLOptions +StdEnvVars
        </FilesMatch>
        <Directory /usr/lib/cgi-bin>
            SSLOptions +StdEnvVars
        </Directory>
    </VirtualHost>
</IfModule>
